#!/bin/bash
#
# ©2013 COPYRIGHT 2013 ROBERT D. CHIN
#
# FILE NAMING CONVENTION FOR ARCHIVING:
# $THIS_FILE_<YYYY-MM-DD_HHMM>
#
# Usage: sh EDIT_HISTORY
#
THIS_FILE="EDIT_HISTORY"
#
# The double # at the beginning of lines below
# are used to delineate the Edit History.
#
## Edit History
##
## After each edit made, update Edit History and version (date stamp string) of
## script.
#
# Calculate revision number by counting all lines starting with "## 2013".
# grep ^ (carot sign) means grep any lines beginning with "##2013".
# grep -c means count the lines that match the pattern.
#
PROJECT_REVISION=$(grep ^"## 2013" -c "EDIT_HISTORY")
PROJECT_REVISION="2013.$PROJECT_REVISION"
PROJECT_REVDATE="October-13-2013 23:37"
clear
echo "Project version: $PROJECT_REVISION"
echo " Last Edited on: $PROJECT_REVDATE"
echo
echo "Bash script name: $THIS_FILE"
echo
echo -n "Press '"Enter"' key to continue."
read ANS
# sed substitutes null for ## at beginning of each line so it is not printed.
# less -P customizes prompt for %f <FILENAME> page <num> of <pages> (Spacebar, PgUp/PgDn . . .)
sed -n 's/^##//'p $THIS_FILE | less -P %f'  page '%dB' of '%D'  (Spacebar, PgUp/PgDn, Up/Dn arrows, press q to quit)' $THIS_FILE
#
#LIC This program, EDIT_HISTORY is under copyright.
#LIC ©2013 Copyright 2013 Robert D. Chin (rdchin at yahoo.com).
#LIC 
#LIC This program is free software: you can redistribute it and/or modify
#LIC it under the terms of the GNU General Public License as published by
#LIC the Free Software Foundation, either version 3 of the License, or
#LIC (at your option) any later version.
#LIC 
#LIC This program is distributed in the hope that it will be useful,
#LIC but WITHOUT ANY WARRANTY; without even the implied warranty of
#LIC MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#LIC GNU General Public License for more details.
#LIC 
#LIC You should have received a copy of the GNU General Public License
#LIC along with this program.  If not, see <http://www.gnu.org/licenses/>.
##
## 2013-10-13 *f_main_init_once added detection for 256-color terminals.
##            *f_show_menu added display font in different colors for a 
##             missing module.
##            *f_menu_item_process fixed case pattern matching menu item 
##             option "Quit", "Return",
##            *f_menu_uncolor created to set font color for unavailable
##             library modules in Application Category Menu.
##
## 2013-10-11 *f_main_init_once created, changed f_initvars_menu_app to
##             allow user-chosen terminal colors to be saved.
##            *f_valid_dir added instructions to exit terminal after $PATH
##             edits are made so they will take effect.
##
## 2013-10-09 *f_main_configure added item option to list module directory.
##            *f_main_download added ability to download Sample Template.
##            *f_menu_app_accounting added brinance, chkbk, clacct.
##            *f_menu_app_audio_editors added cutmp3.
##            *f_menu_app_bloggers created, added charm.
##            *f_menu_app_cdrippers added cddao, cdrskin, cdw.
##            *f_menu_app_file_splitters added cut.
##            *f_menu_app_file_transfer added wget.
##            *f_menu_app_music_players3 created, added ccx2, clxmms, ncxmms2,
##             and xmms2-client-cli.
##            *f_menu_app_radio added pyradio.
##            *f_menu_app_sys_monitors added rcconf, sysv-rc-conf, ntsysd.
##
## 2013-10-08 *f_menu_item_info changed to fix directory not found error when
##             cli-app-menu.sh is not in same directory as module libraries.
##            *f_menu_item_process changed for compatibility with Main Menu.
##            *Main Menu rework menu structure to be consistent with other
##             menus, see 9/15, 9/16 entries.
##
## 2013-10-07 *f_menu_main_configure added code to download EDIT_HISTORY
##             if file is missing.
##            *f_menu_term_color added to change font/background colors.
##            *f_term_color added to change font/background colors.
##            *Main Menu item "About CLI menu" added code to download
##             EDIT_HISTORY if file is missing.
##
## 2013-10-01 *f_initvars_menu_app reworked to allow directory and 
##             file verification.
##            *f_valid_dir added to allow directory verification.
##            *f_valid_files added to allow directory/file verification.
##
## 2013-09-26 *cli-app-menu.sh, lib_cli-common.lib and all f_mod_apps* files
##             changed to allow cli-app-menu.sh to reside in a different
##             folder/directory and to correct a f_show_menu parameter
##             passing bug.
##
## 2013-09-25 *f_menu_app_video_editors added exiftool, mediainfo.
##            *f_menu_app_audio_editors added exiftool, mediainfo.
##            *f_menu_app_image added exiftool.
##            *f_ask_which_module_download fixed downloading. 
##            *f_menu_main_download fixed module downloading.
##
## 2013-09-24 *cli-app-menu.sh, lib_cli-common.lib added variable THIS_DIR to
##             allow scripts and libraries to be run from other directories. 
##            *f_application_install added exiftool case pattern matching.
##            *f_ask_which_module_download reworked, added input validation.
##            *f_menu_app_file_delundel added scalpel.
##            *f_menu_app_screen_savers added quit codes.
##            *f_module_match enhanced error checking.
##            *Main Menu item "List Applications", "Search Applications"
##             error messages simplified.
##            *README updated file location instructions.
##
## 2013-09-23 *f_menu_main_configure "LIST_APPS" menu item clarify instructions.
##            *f_mod_apps-office.lib rework finished.
##
## 2013-09-20 *f_mod_apps-network.lib rework finished.
##            *f_mod_apps-system reworked.
##
## 2013-09-17 *f_find_NIC reworked to add validity checking.
##            *f_mod_apps-network.lib reworked.
##
## 2013-09-16 *f_cat_menu_item_process copied from f_menu_item_process for
##             use in the Main Menu, and Application Categories Menu,
##             f_menu_cat_applications. It was simpler to use existing code
##             than to make those menus work with the reworked code.
##            *f_menu_item_process reworked to allow for category menus.
##            *mod_apps_audio.lib, education, games, image, internet,
##             screensaver, video.
##
## 2013-09-15 *f_menu_app* menus started restructuring with application
##             information included in the menu data. This eliminated the
##             need for case pattern matching and reduced file sizes
##             considerably. To support this new functionality, a number of
##             new functions had to be written.
##            *f_eval_funct created.
##            *f_menu_item_process was reworked.
##            *f_menu_item_valid created.
##            *f_menu_item_info created.
##            *f_press_key created.
##            *f_quit_app_clause created.
##            *f_run_and_exit created.
##
## 2013-09-11 *f_menu_app_packet_tools deleted wireshark (GUI) and
##              added tshark (CLI for wireshark).
##            *f_ask_which_module_download fixed not asking which branch.
##            *f_module_match fixed XSTR conflict by passing $1 as input.
##
## 2013-09-10 *Main Menu item "Configure" added, f_menu_main_configure.
##             item "Download" added f_menu_main_download.
##
## 2013-09-09 *f_menu_app_binhex_editors added hexer, vbindiff, xdelta,
##             xdelta3.
##            *f_menu_app_file_burn added cdck, lsdvd.
##            *f_menu_app_file_checksum added cdck, cfv.
##            *f_menu_app_file_compression added lhasa, lzma, lzip, lzop,
##             pdlzip, rzip, unp.
##            *f_menu_app_file_encryption added nasty, rephrase
##            *f_menu_app_file_find added duff, fdupes, file, missidentify,
##             rdfind, rrep.
##            *f_menu_app_file_managers added ncdt, lfm.
##            *f_menu_app_file_operations added cdargs, dares, ddrescue,
##             magicrescue, myrescue, safe-rm, scrub, wipe.
##            *f_menu_app_file_splitters added hoz.
##            *f_menu_app_pdfps added comparepdf, pdfgrep.
##            *f_menu_app_sys_disks added agedu, di, discus.
##            *f_menu_app_sys_logs added colortail, inotail, monkeytail.
##            *f_menu_app_sys_mainboard added mbw.
##            *f_menu_app_sys_monitors added tyload.
##            *f_menu_app_sys_other added colortest, cpm.
##            *f_menu_app_sys_peripherals added cdde, setcd.
##            *f_menu_app_text_compare added dwdiff.
##            *f_menu_app_text_file_editors added pyp, rrep.
##
## 2013-09-08 *f_menu_app_calendar added hebcal, jcal, lunar.
##            *f_menu_app_clocks added leave, tzwatch.
##            *f_menu_app_education added kon2.
##            *f_menu_app_file_checksum created under "File/Dir" app menu.
##            *f_menu_app_internet added cfv.
##            *f_menu_app_note added nodau, note.
##            *f_menu_app_text_converters added wpd2odt, wpg2odg, wps2odt.
##            *f_menu_app_text_tools added sdcv.
##            *f_menu_app_todo added w2do.
##            *f_menu_app_video added melt.
##            *Main Menu item "Search" used "less" switch for color output.
##
## 2013-09-07 *f_menu_app_clocks added binclock.
##            *f_menu_app_databases added couchdb.
##            *f_menu_app_education added metar, seesat5, weather, tide.
##            *f_menu_app_file_delundel created. Added safe-rm, scrub.
##             Moved shred, wipe, foremost, photorec, safecopy, trash-cli
##             from f_menu_app_file_operations.
##            *f_menu_app_file_managers added lfm, ncdt.
##            *f_menu_app_file_operations added cdargs, mmv, mrename.
##            *f_menu_app_file_splitters added hoz.
##            *f_menu_app_games_word added hodie.
##            *f_menu_app_image_graphics added welcome21.
##            *f_menu_app_lan added wuzzah.
##            *f_menu_app_math axiom, dicelab, mathomatic, ministat,
##             num-utils, open-axiom, plotutils,  pi, pspp, relational-cli,
##             and stda.
##            *f_menu_app_note added tina, worklog.
##            *f_menu_app_screen_savers added termsaver.
##            *f_menu_app_sys_disks added agedu.
##            *f_menu_app_sys_health added cpuburn.
##            *f_menu_app_sys_others added script, ttyrec.
##            *f_menu_app_sys_monitors added atsar, acpi, acpitail.
##            *f_menu_app_sys_screens added away, screenie.
##            *f_menu_item_process fixed improper setting of MENU_ITEM for
##             "man <appname>" or "<appname> --help" or anything w/arguments.
##            *f_show_menu fixed font for Application Category Menu if last
##             module in menu is not loaded (in normal not bold font).
##             This made the prompt echo in normal font too.
##
## 2013-09-06 *f_menu_app_sample_template was rewritten for flexibility
##             in nesting.
##            *f_menu_scat_sample_template was rewritten for flexibility
##             in nesting.
##            *f_show_menu added case pattern "AAC" for Download menu.
##            *lib_cli-menu-cat.lib rewritten to be consistent with templates.
##             deleted CHOICE_CAT variable.
##            *Main Menu item "Download" made slight adjustments.
##            *mod_apps-* were rewritten for flexibility in nesting.
##             No more CHOICE_SCAT/TCAT/APP variables.
##             Scratch variables Bxx, Mxx used in Until-loop are unset before
##             exiting mod_apps-*.
##            *README deleted references to CHOICE_CAT, CHOICE_SCAT,
##             CHOICE_TCAT, CHOICE_APP, variables.
##
## 2013-09-05 *f_menu_item_process created based on f_common_app/scat/tcat_menus.
##            *f_scat_bad_menu_choice deleted.
##            *f_tcat_bad_menu_choice deleted.
##            *f_show_max renamed to f_show_max_items.
##            *mod_apps-audio.lib, mod_apps-databases.lib, mod_apps_sample-
##             template.lib, mod_apps-education.lib, mod_apps-filedir.lib
##             were rewritten for flexibility in nesting.
##
## 2013-09-04 *f_application_bad_menu_choice deleted.
##            *f_ask_which_branch_download reworked.
##            *f_ask_which_branch_download preserved default answers, more robust.
##            *f_bad_menu_choice created based on f_application/scat/cat_bad_menu_choice.
##            *f_common_app_menu deleted.
##            *f_common_scat_menu deleted.
##            *f_common_tcat_menu deleted.
##            *f_download_file invoke common library.
##            *f_initvars_menu_app simplify the initialization of variables.
##            *f_menu_app_hamradio created; added hamexam. Moved aldo, cw,
##             cwcp, ebook2cw, morse, morsegen, qrq, tlf from the education
##             module f_menu_app_education.
##            *f_wget_file invoke common library. Changed to always ask which branch.
##            *Main Menu item "Download" fixed script downloading, more robust.
##
## 2013-09-01 *f_show_menu enhanced the Application Categories Menu
##             to indicate whether or not a module file is accessible by
##             changing the menu item font.
##            *f_menu_cat_applications changed structure to embed the module
##             file names in the menu. Needed for enhancement to f_show_menu.
##            *f_menu_app_text_editors2 changed "jed" description in menu,
##             Added jmacs, jpico, jstar, rjoe. Deleted "the" text editor.
##            *f_menu_app_text_editors3 added "the" text editor.
##            *Main Menu changed editor from "joe" to "jed" more user-friendly,
##             added menu item "Update LIST_APPS".
##
## 2013-08-30 *f_menu_app_lanwan deleted.
##            *f_menu_app_lan created added arping, ip, ip addr, ip link,
##             ip neighbor, ping, sipcalc, ss, subnetcalc.
##            *f_menu_app_nic_tools added ip, ip address, ip neighbor.
##            *f_menu_app_wan created added dig, dnsstop, ip ip route, mtr,
##             nslookup, ping, route, speedometer, ss, traceroute.
##            *f_show_max created.
##            *f_show_menu added back the help instructions.
##            *Main Menu replaced "more -d" with "less -P", custom prompt.
##            *README added instructions "HOW-TO Add a new menu item".
##
## 2013-08-29 *f_application_help added case pattern *--version.
##            *f_application_install_question added.
##            *f_menu_app_audio_editors added avinfo.
##            *f_menu_app_binhex_editors created; added bbe, bvi, dhex;
##             moved beav from f_menu_app_text_editors.
##            *f_menu_app_calculators added apcalc, concalc, genius, qualc,
##             rpncalc, wcalc.
##            *f_menu_app_contacts created, added abook.
##            *f_menu_app_databases created, added ara, edb, freedb, lbdb,
##             mysql, postgresql, sqlite, task-database, tokyocabinet.
##            *f_menu_app_downloaders added axel.
##            *f_menu_app_education added ebook2cw, morsegen, qrq, tlf.
##            *f_menu_app_file_conversion created by copying from function
##             f_menu_app_text_converters.
##            *f_menu_app_file_deletion deleted.
##            *f_menu_app_file_managers added pilot.
##            *f_menu_app_file_operations created, added advcpmv, xd,
##              consolidated file deletion/recovery/backup applications under
##              a single menu.
##            *f_menu_app_file_recover deleted.
##            *f_menu_app_file_splitters added lxsplit.
##            *f_menu_app_file_transfer added advcpmv.
##            *f_menu_app_firewalls added knocker.
##            *f_menu_app_games_arcade added nsnake, zsnake.
##            *f_menu_app_games_board added gnubg.
##            *f_menu_app_games_card added freecell.
##            *f_menu_app_games_puzzle added greed, vitetris.
##            *f_menu_app_games_rpg added gearhead, overkill.
##            *f_menu_app_games_simulation added ztrack.
##            *f_menu_app_games_strategy added empire.
##            *f_menu_app_games_word added rl.
##            *f_menu_app_instant_messaging added bti.
##            *f_menu_app_lanwan added sipcalc, subnetcalc.
##            *f_menu_app_music_players added audiotag, dcd.
##            *f_menu_app_music_taggers created; added audiotag, lltag,
##             and musictag.
##            *f_menu_app_news_readers added cortex, hacker-top, reddit-top.
##            *f_menu_app_note added diary, diary-f, org-mode.
##            *f_menu_app_packet_tools added packit.
##            *f_menu_app_pdfps added pstotext, ps2eps, sdf, sdop.
##            *f_menu_app_remote_connection added grive.
##            *f_menu_app_screen_savers added ticker.
##            *f_menu_app_sys_backup deleted from mod_apps-filedir.lib.
##            *f_menu_app_sys_logs added since.
##            *f_menu_app_sys_monitors added conky-cli
##            *f_menu_app_sys_screens added splitvt.
##            *f_menu_app_sys_software added apt-file.
##            *f_menu_app_text_compare added since.
##            *f_menu_app_text_converters added ebook2cw, unoconv, unrtf, wp2x,
##             xmlto.
##            *f_menu_app_text_editors added aoeui, e3em, e3vi, e3pi,
##             e3ne, e3ws, efte, elvis-console, fte-console, fte-terminal.
##            *f_menu_app_text_editors2 created; added jed-extra, jove, le,
##             ledit, levee, mg, nano-tiny, ne, nvi, the.
##            *f_menu_app_text_editors3 created; vile, vim-nox, vim-scripts,
##             vim-tiny, vim-outliner, wordgrinder.
##            *f_menu_app_text_markup_language created, added sisu, stx2any,
##             texinfo, udo, and moved doconce.
##            *f_menu_app_text_tools added acheck, dict, dictd.
##            *f_menu_app_todo added diary, diary-f, devtodo, org-mode, tdl.
##            *f_web_site simplified case pattern matching.
##            *Main Menu items "Search Applications" loop for multiple searches.
##            *mod_apps-databases.lib created, added f_menu_app_databases.
##
## 2013-08-25 *Main Menu items rewrote "Documentation", "Download",
##             "Edit History", "License", List Applications", and "Search
##             Applications".
##
## 2013-08-22 *f_ask_which_branch_download created asks which git branch to use.
##            *f_ask_which_module_download created asks modules to download.
##            *f_load_module renamed to f_download file.
##            *f_module_match created determines modules to download.
##            *f_scat_bad_menu_choice fixed CHOICE_APP to CHOICE_SCAT.
##            *f_tcat_bad_menu_choice fixed CHOICE_APP to CHOICE_TCAT.
##            *f_wget_file created to do the actual wget download of files.
##            *lib_cli-menu-cat.lib replaced f_load_module with f_download_file.
##            *Main Menu item "Download" item now downloads both menu script
##             and/or software modules from git branch STABLE or TESTING.
##
## 2013-08-21 *cli-app-menu.sh inserted an echo command at a blank line.
##            *f_application_install improved error messages.
##            *Main Menu item "List Applications", "Search Applications" added
##             error message and instructions if file LIST_APPS was missing.
##
## 2013-08-20 *cli-app-menu.sh fixed date string missing quotation mark.
##             Reworked "List Applications" and "Search Applications" items.
##            *f_application_web_install sorted alphabetically case patterns.
##            *f_create_LIST_APPS rewritten so includes menu titles,
##             application names and descriptions in human readable form.
##            *f_load_module fixed PRESS_KEY statements.
##            *f_menu_app_accounting added clipf, fixed case pattern matching.
##            *f_menu_app_cdrippers fixed a comment line missing "#".
##            *f_menu_app_clocks added tbclock, vtclock.
##            *f_menu_app_file_encryption added gnupgp.
##            *f_menu_app_file_managers added exiftool, jhead.
##            *f_menu_app_lanwan added dnstop.
##            *f_menu_app_image_graphics added exiftool, jhead.
##            *f_menu_app_instant_messaging added climm.
##            *f_menu_app_music_players added clvc, mcplay, mjs, mp3blaster,
##             opencubicplayer, orpheus.
##            *f_menu_app_music_players2 is a new audio menu added mpd,
##             moosic, mpc, draii, pms, mussort, vimpc, vitunes.
##            *f_menu_app_nic_tools added macchanger.
##            *f_menu_app_sys_disks added tdu.
##            *f_menu_app_sys_health added aide.
##            *f_menu_app_sys_logs added lnav.
##            *f_menu_app_sys_screens added twin.
##            *f_menu_cat_applications fixed "Games" item module name.
##            *f_test_dash moved back to cli-app-menu.sh added comments.
##            *LISTAPPS updated for new apps, README updated for new audio menu.
##
## 2013-08-19 *f_create_LIST_APPS added to create file LIST_APPS automatically.
##            *f_load_module deleted test code.
##            *f_menu_cat_applications added PRESS_KEY=0 for case statement.
##            *f_show_menu, f_choice_array improved documentation of awk.
##            *Main Menu item "List Applications" changed to use file LIST_APPS.
##            *README updated documentation on "FILE LOCATIONS of cli-app-menu
##             project", and "Known problems and limitations", and
##             "HOW-TO Add a new menu item".
##
## 2013-08-17 *f_menu_cat_applications edited and added f_load_module, broke out
##             application category apps into different files.
## 
## 2013-08-16 *f_common_scat_menu fixed case pattern matching for CHOICE_SCAT.
##
## 2013-08-13 *f_application_install added ability to install with package
##             managers pacman, slackpkg (in addition to apt, rpm).
##            *f_menu_app_file_burn improved help messages.
##            *f_menu_app_text_compare added cmp.
##            *f_menu_app_text_tools added wc.
##            *f_menu_app_sys_peripherals added w.
##            *README updated.
##
## 2013-08-09 *f_application_error improved error code 1, 2 messages to help
##             when missing filenames/operands. Trapped error code 1 when
##             not really an error but a result (as in diff apps).
##            *f_application_help added test if app missing, w/install option.
##            *lib_cli-common.lib added f_display_error_code.
##            *lib_cli-menu-apps.lib added "Press Enter key" in some apps.
##
## 2013-08-08 *EDIT_HISTORY cleaned up grammatically.
##            *f_menu_app_text_tools added aspell, hunspell, ispell, spell.
##            *lib_cli-menu-apps.lib formatted man and --help in single quotes.
##            *Main Menu item "Download" fixed to also include the *.lib
##             library files when downloading from the project's github
##             repository Stable branch. This was due to copying the library
##             files from Testing to Stable branch.##
##
## 2013-08-07 *f_application_install added pattern matching for atool apps.
##            *f_menu_cat_file_management added items "Compress", "Edit".
##            *f_menu_cat_games changed menu to include descriptions.
##            *f_menu_cat_games changed item name
##             from "Simulation Games"
##               to "Sims/Anims".
##            *f_menu_app_file_compression added acat, als, apack, aunpack,
##             and unace.
##            *f_menu_app_games_simulation added bb, sl, .
##            *f_menu_app_games_word added figlet, rev, toilet.
##            *f_menu_app_image_graphics added bb, sl, Star Wars ASCII movies.
##            *f_menu_app_text_editors added zile help, 
##            *f_menu_app_text_tools added spell.
##            *lib_cli-menu-apps.lib added "Press Enter key" in some apps.
## 
## 2013-08-06 *All script files now have a separate revision date.
##            *lib_cli-menu-apps.lib added "Press Enter key" in some apps.
##
## 2013-08-01 *lib_cli-menu-apps.lib added help, detect NIC for speedometer.
##            *Main Menu added item "Search Applications".
##
## 2013-07-31 *lib_cli-menu-cat.lib fixed by adding f_menu_cat_network and
##             f_menu_tcat_network_monitors after they were accidently missing
##             when cli-app-menu.sh was split into several library files.
##
## 2013-07-29 *f_menu_app_games_simulation added Star Wars ASCII movie.
##
## 2013-07-27 *Main Menu item "Download" added ability to download from Stable
##             or Testing repositories.
##
## 2013-07-26 *Split functionality of cli-app-menu.sh into several library
##              files: lib_cli-common.lib, lib_cli-menu-cat.lib,
##                     lib_cli-menu-apps.lib
##
## 2013-07-21 *f_application_error edited message to note app error messages.
##            *f_menu_app_calculators added dc. 
##
## 2013-07-19 *f_menu_app_calculators added dc.
##            *f_menu_app_file_compression added xz, unxz, xzcat, xzgrep.
##            *f_menu_app_firewalls added strobe.
##            *f_menu_app_network_bandwidth added statnet, trafshow.
##            *f_menu_app_network_bandwidth tweaked pktstat messages. 
##            *f_menu_app_network_monitors added netwatch.
##            *f_menu_app_nic_tools added netload.
##            *f_menu_app_pdfps added pdftk.
##            *f_menu_app_sys_disks added hdparm.
##            *f_menu_app_sys_backup added dtrx.
##            *f_menu_app_sys_logs added ccze.
##            *f_menu_app_sys_screens added dvtm, fbterm, vlock.
##            *f_menu_app_web_browsers added surfraw.
##
## 2013-07-18 *Case pattern matching re-ordered to allow <application><options>.
##            *f_menu_app_sys_disks added lsblk.
##            *f_menu_app_file_encryption added lspgpot.
##            *f_menu_app_sys_disks added dfc.
##            *f_menu_app_lanwan added dig.
##
## 2013-07-14 *f_menu_app_nic_tools ethtool added help and f_find_nic.
##
## 2013-07-13 *f_menu_cat_system fixed "Screens" case pattern matching.
##            *f_menu_app_podcatchers fixed bashpodder case pattern matching.
##            *f_menu_app_sys_software shortened description of aptoncd to fit.
##
## 2013-07-12 *f_menu_tcat_network_monitors added f_menu_app_network_bandwidth.
##            *f_menu_app_network_bandwidth added nload, pktstat.
##            *f_menu_app_firewalls added iptstate.
##
## 2013-07-11 *f_choice_array rewrote awk statement so CHOICE array now works
##             with menu choice names with 2 words, as long as second word is
##             unique. i.e. "ip", "ip addr", "ip link" names now all work.
##            *f_test_dash added to warn user to switch environment to BASH.
##
## 2013-07-03 *README added List of variables and Special Menu Option Markers.
##            *Deleted the two lists mentioned above and all case pattern
##             matching simplified using * wildcards reducing file size by 52KB.
##            *f_menu_app_instant_messaging fixed emacs-jabber case pattern
##             matching.
##            *f_menu_app_calendar fixed  emacs-calfw case pattern matching.
##            *f_menu_app_calendar fixed pcal case pattern matching.
##            *f_menu_cat_text fixed compare case pattern matching.
##            *f_menu_app_sys_peripherals fixed lspcmcia case pattern matching.
##
## 2013-06-11 *f_menu_app_games_card fixed canfield case pattern matching.
##            *f_menu_app_games_card deleted cribbage warning message.
##            *f_menu_app_games_quiz arithmetic added warning message.
##            *f_menu_app_games_simulation atc added warning message.
##            *f_menu_app_games_word pig added warning message.
##
## 2013-06-10 *Added help messages, added PRESS_KEY statements.
##            *cli-app-menu_dash.sh had fixes back-ported for STABLE branch.
##            *f_menu_app_education morse added warning message.
##            *f_menu_app_games_arcade added bastet, netris, petris,
##             added mssgs.
##            *f_menu_app_games_quiz morse added warning message.
##            *f_menu_app_games_puzzle bcd, netris, ppt added warning message.
##            *f_menu_app_games_puzzle petris added help message.
##            *f_menu_app_file_viewers deleted jless, added less.
##            *Main Menu item "Documentation" changed to display README file.
##
## 2013-06-08 *Deleted program comments.
##            *Main Menu item "License" fixed case pattern matching.
##            *README added program comments.
##            *f_application_error fixed case pattern matching of error numbers.
##            *f_application_run fixed case pattern matching of error numbers.
##            *f_choice_array added to handle numeric input for menu choices.
##             Numeric input is handled by an array CHOICE[XNUM].
##            *f_common_scat_menu added f_common_tcat_menu, f_common_app_menu.
##            *f_menu_app_firewalls fixed iptables help comment.
##            *f_menu_app_network_monitors fixed netstat, opennms, sntop
##             help comments.
##            *f_menu_app_sys_health arp-scan fixed help comment.
##            *f_menu_app_text_converters fixed txt2pdbdoc help comment.
##            *f_menu_cat_file_management fixed FTP/HTTP case pattern matching.
##            *f_menu_cat_office fixed calculators, notebooks, presenters,
##             spreadsheets case pattern matching.
##            *f_menu_cat_system fixed monitors case pattern matching.
##            *f_quit_scat_menu, deleted f_quit_tcat_menu, f_quit_app_menu.
##
## 2013-06-08 *cli_app_menu_dash added file to accomodate DASH environment
##             used by Ubuntu-based linux distributions. DASH does not handle
##             arrays without errors so this version does not use arrays.
##
## 2013-06-04 *f_menu_app_sys_backup fixed rsync, tar case pattern matching.
##            *f_menu_app_file_compression fixed function name.
##
## 2013-06-03 *All applications changed to allow only lower-case app names when
##             followed by options.
##            *Fixed typo "DELIMETER" changed to "DELIMITER".
##            *f_menu_cat_* and f_menu_app_* now sorted in alphabetic order.
##            *f_menu_cat_office fixed f_menu_app_clocks case pattern matching.
##            *f_menu_cat_video fixed delimiter.
##            *f_application_install cleaned up messages.
##            *f_application_web_install added.
##            *f_menu_app_audio_editors fixed ffmpeg case pattern matching.
##            *f_menu_app_clocks added.
##            *f_menu_app_file_burn added.
##            *f_menu_app_file_compression added.
##            *f_menu_app_file_transfer shortened woof description.
##            *f_menu_app_firewalls fixed arptables case pattern matching.
##            *f_menu_app_music_players fixed vlc case pattern matching. 
##            *f_menu_app_network_monitors deleted ss from network monitor
##            *f_menu_app_network_sharing shortened woof description.
##            *f_menu_app_sys_peripherals fixed menu spacing.
##            *f_menu_app_todo fixed menu spacing.
##            *f_menu_app_video_editors fixed ffmpeg case pattern matching.
##            *f_menu_app_video_editors fixed delimiter.
##            *f_menu_app_video_editors shortened mpgtx description.
##            *f_menu_app_video_players fixed vlc case pattern matching.
##            *f_menu_app_video_players fixed delimiter.
##
## 2013-06-02 *f_menu_cat_video added f_menu_app_video_editors,
##             and f_menu_app_video_players.
##            *f_menu_app_calendar added emacs-calfw.
##            *f_menu_app_email added gnus, heirloom-mailx, mu4e.
##            *f_menu_app_file_managers added dired.
##            *f_menu_app_firewalls added PortBunny.
##            *f_menu_app_image_graphics added fbv, fim, jfbview.
##            *f_menu_app_instant_messaging added emacs-jabber.
##            *f_menu_app_irc_clients added erc, scrollz.
##            *f_menu_app_lan_chat added weechat.
##            *f_menu_app_music_players added herrie, mpg123, mplayer2,
##             pianobar, shell-fm, vlc.
##            *f_menu_app_network_chat renamed to f_menu_app_lan_chat.
##            *f_menu_app_pdfps added fbdjvu, fbpdf, jfbview.
##            *f_menu_app_radio added pianobar, shell-fm.
##            *f_menu_app_sys_disks added gt5.
##            *f_menu_app_sys_other added DeSmuME.
##            *f_menu_app_sys_screens added dtach, dvtm.
##            *f_menu_app_text_editors added dex, JED.
##            *f_menu_app_video deleted.
##            *f_menu_app_video_editors added avidemux, handbrake-cli.
##            *f_menu_app_video_players added mplayer2.
##            *f_menu_app_web_browsers added retawq.
##
## 2013-06-01 *f_menu_cat_file_management added f_menu_app_file_transfer,
##             and f_menu_app_sys_backup, f_menu_app_file_splitters.
##            *f_menu_cat_image renamed "Image Tools" to "Tools" to avoid
##             similarity to "ImageMagick".
##            *f_menu_app_audio_editors added ecasound, ffmpeg.
##            *f_menu_app_bittorrent added aria2, deluge, mldonkey,transmission.
##            *f_menu_app_calendar added clcal, mencal.
##            *f_menu_app_file_splitters added lxsplit, split.
##            *f_menu_app_file_transfer added woof.
##            *f_menu_app_instant_messaging added naim.
##            *f_menu_app_music_players deleted ffmpeg.
##            *f_menu_app_network_sharing added ncpfs, woof.
##            *f_menu_app_sys_backup added atool, p7zip.
##            *f_menu_app_sys_health added lynis.
##            *f_menu_app_todo added doneyet, hnb, tudu, yokadi, cclock.
##
## 2013-05-30 *f_menu_app_file_recover fixed trash-cli case pattern matching.
##
## 2013-05-29 *f_menu_app_audio_editors fixed avconv, sox case pattern matching.
##
## 2013-05-28 *f_menu_app_sys_health fixed stress help "man stress".
##
## 2013-05-23 *f_menu_app_sys_information added blkid, pccardctl, lsblk, lscpu,
##             slabtop.
##            *f_menu_app_file_managers added findmnt.
##            *f_menu_app_sys_process added pswatcher, pwdx, sysctl.
##            *f_menu_app_network_monitors added bmon, nagios3, OpenNMS.
##            *f_menu_app_sys_monitors added cacti, rrdtool, swatch.
##            *f_menu_app_sys_logs added swatch.
##            *f_menu_app_sys_health added stress.
##            *f_menu_app_sys_information deleted.
##            *f_menu_app_sys_mainboard added.
##            *f_menu_app_sys_peripherals added.
##
## 2013-05-20 *f_application_help added feature to install app automatically,
##             if needed.
##
## 2013-05-18 *Optimize sudo case pattern matching code.
##            *f_menu_app_firewalls added arptables, arptables.
##            *f_menu_app_lanwan added arping, ss.
##            *f_menu_app_network_monitors added nethogs, ntop, pmacct,
##             vnstat, ss.
##            *f_menu_app_sys_process added.
##            *f_menu_app_sys_health added arpon, arpalert, arpwatch, arp-scan.
##            *f_menu_app_sys_monitors added sar, nmon, last.
##
## 2013-05-16 *f_menu_app_sys_software added aptoncd.
##            *f_menu_app_sys_software added apt-* case pattern matching.
##            *f_menu_app_sys_software added dpkg-* case pattern matching.
##            *f_menu_app_sys_software added help comments for aptitude, zypper.
##            *f_menu_app_sys_screens added help comments for screen.
##
## 2013-05-15 *f_menu_app_music_players added cdcd, cplay, mcdp, pytone, yauap.
##            *f_menu_app_sys_monitors improved menu descriptions.
##            *f_menu_app_sys_software improved help for apt, dpkg, rpm, yum.
##            *f_menu_app_instant_messaging fixed barnowl case pattern matching.
##            *f_menu_app_sys_software fixed YaST case pattern matching.
##            *Changed help comments to a consistent format.
##
## 2013-05-14 *Reordered functions to match the menus.
##            *f_menu_app_sample_template fixed comment line with #MXX so it is
##             not printed in "List Applications".
##            *f_menu_app_games_puzzle fixed bastet displaying twice in menu.
##             This is due to a comment referring to bastet not having the
##             third field #MGF to prevent awk from printing it in a menu.
##            *f_menu_app_acconting added ledger, hledger, hledger plugins.
##            *f_menu_app_file_deletion added.
##
## 2013-05-13 *f_menu_app_sys_backup added bashburn, burn, cdrecord, xorriso,
##             mkcd, mybashburn, simpleburner.
##            *f_menu_app_speech_synthesis added edbrowse.
##            *f_menu_app_video added yougrabber, youtube-dl.
##            *f_menu_app_education added grass.
##            *Cleaned up menu displays.
##
## 2013-05-11 *f_menu_cat_audio added, 
##            *f_menu_app_cdrippers added. Added acripper, cdparanoia, crip,
##              jack, lxdvdrip, ripit, rubyripper.
##            *f_menu_app_audio_editors added.
##            *f_menu_app_music_players added.
##            *f_menu_app_radio added.
##            *f_menu_app_speech_synthesis added.
##
## 2013-05-05 *f_menu_app_nic_tools fixed nictools-pci case pattern matching.
##
## 2013-05-03 *f_application_help changed to set CHOICE_APP=-1.
##            *Sub-menus added comments.
##
## 2013-05-03 *f_menu_app_audio moved any video apps.
##            *f_menu_app_video added. Added video apps.
##            *f_app_web_site improved case statements and documentation.
##            *Main Menu item "List all applications" improved documentation.
##
## 2013-04-28 *Added "Trouble-shooting a new menu item".
##            *Changed sudo processing to allow lowercase commands only.
##            *f_menu_app_packet_tools added.
##            *f_menu_app_firewalls added.
##            *f_menu_app_lanwan added. Added ip, ip addr, ip link,
##                               ip neighbor, nslookup.
##            *f_menu_app_nic_tools added. Added ethtool, mii-tool, mii-diag,
##                                  nictools-pci, ifplugstatus.
##            *f_menu_app_network_sharing added.
##            *f_menu_app_system_software added.
##            *f_application_install fixed typo "systat" to "sysstat".
##
## 2013-04-26 *f_menu_app_education added typespeed.
##            *f_menu_app_file_find added updatedb and help comments for locate.
##
## 2013-04-23 *f_menu_app_pdfps added. Moved all pdf and ps apps to this menu.
##
## 2013-04-11 *f_menu_cat_personal_organizers deleted.
##            *f_menu_cat_office added.
##            *f_menu_app_presentation added. Added tpp.
##
## 2013-04-10 *f_menu_sys_health added. Added tripwire help info.
##            *f_menu_app_text_compare added diffpdf.
##            *f_menu_app_sys_information added acpitool.
##
## 2013-04-09 *f_menu_sys_health added. Added chkrootkit, rkhunter, tripwire.
##            *f_menu_sys_monitors added chkconfig.
##
## 2013-04-08 *f_menu_cat_file_management added.
##            *f_menu_app_file_encryption added. Added bcrypt, ccrypt, crypt,
##             mcrypt, pgp, scrypt, truecrypt, zcrypt.
##            *f_menu_app_file_find added.
##            *f_menu_app_file_viewers added. Added more.
##            *f_menu_app_file_recover added.
##            *f_menu_cat_system added.
##            *f_menu_app_sys_backup added. Added rsync, tar, gzip, gunzip,
##             zip, unzip.
##            *f_menu_app_sys_disks added. Added du, pydf.
##            *f_menu_app_instant_messaging added barnowl.
##
## 2013-04-07 *f_menu_cat_text added.
##            *f_menu_app_text_compare added.
##            *f_menu_app_text_converters added.
##            *f_menu_app_text_tools added.
##            *f_menu_cat_image added.
##            *f_menu_app_imagemagick added.
##            *f_menu_cat_organizer added.
##            *f_menu_app_calendar added.
##            *f_menu_app_todo added.
##            *f_menu_app_calendar_todo deleted.
##            *f_menu_app_calendar added calcurse, ccal, gcal, pcal.
##
## 2013-04-06 *f_menu_app_calendar_todo added saytime.
##            *f_menu_app_education added diatheke, liflines, gtypist.
##            *f_menu_app_file_managers added find, locate, shred, foremost, 
##             photorec, safecopy.
##            *f_menu_app_image_graphics added fbi, animate, composite, compare,
##             conjure, convert, display, identify, import, mogrify, montage,
##             stream.
##            *f_menu_app_text_tools added fbgs.
##
## 2013-04-04 *f_menu_app_network_config added speedometer.
##            *f_menu_app_network_monitor added jnettop, sntop.
##
## 2013-04-02 *Fixed sudo which ran applications only w/o parameters.
##            *"Press Enter key to continue" fixed in some apps.
##            *f_find_NIC added to find NICs (Network Interface Cards).
##            *f_menu_app_network_monitors added ifstat.
##            *f_menu_app_sys_monitors added free, iostat, lshw, lspci, pidstat,
##             ps, mpstat, uptime, vmstat.
##
## 2013-04-01 *f_menu_app_network_monitors added netstat, slurm.
##            *f_menu_app_text_editors added zile.
##            *f_menu_app_sys_monitors added tload.
##            *Main Menu item "Download" added.
##
## 2013-03-29 *f_menu_app_network_monitors added kismet, snort, tcpdump,
##             and wireshark.
##            *f_menu_app_network_config added iwlist.
##            *f_menu_app_sys_monitors added clamscan, freshclam.
##
## 2013-03-28 *Updated "Help and Features" items.
##            *Moved "Disk Status" from Main Menu to System Information Menu.
##            *Main Menu added item "List Applications".
##            *f_menu_app_text_tools added antiword application.
##            *f_menu_app_games_arcade added asciijump.
##            *f_menu_app_calendar_todo added binary-clock, clockywock,
##             grandfatherclock.
##            *Fixed pesky "Press Enter key to continue" inconsistency in menus.
##            *Made miscellaneous small fixes.
##            *Removed blank lines.
##
## 2013-03-26 *f_quit_app_menu fixed added PRESS_KEY=0 for case statement.
##            *Application menu case pattern matching,
##             change from ' '[-]*
##             change to ' '* to allow more than just OPTIONS but also [FILES].
##            *Added ability to enter application [OPTIONS] on menu choice line.
##            *f_application_bad_menu_choice sets CHOICE_APP=-1 for all strings.
##             and sets PRESS_KEY=0 so menu is immediately redisplayed.
##            *f_web_site optimized code and can enter web browser application
##             name with(out) web site and with(out) -OPTIONS.
##            *f_option_press_enter_key added introduce PRESS_KEY variable and
##             replaces f_menu_app_press_enter.
##
## 2013-03-23 *Cleaned up comments to optimize for an 80 column display.
##            *f_menu_app_calendar_todo cleaned up apps display when run.
##
## 2013-03-22 *f_subcat_bad_menu_choice added.
##            *f_applications_bad_menu_choice added.
##            *f_menu_app_sys_information added.
##            *Standardized help messages.
##            *README, EDIT_HISTORY now can be read by typing "sh <FILENAME>".
##            *Main Menu added item "Update Edit History".
##
## 2013-03-21 *Fixed all menus different responses to f_menu_app_press_enter_key
##             when CHOICE_* is alpha versus numeric. Force to be numeric before
##             calling f_menu_app_press_enter_key since it uses numeric tests.
##             Before, alpha CHOICE_* would ignore f_menu_app_press_enter_key.
##            *Cleaned up many extraneous messages, "Press Enter key..."
##            *f_menu_app_network_monitor iftop changed to allow user to choose
##             what network interface to monitor.
##
## 2013-03-19 *Main Menu item "Edit History" changed to test if file exists.
##            *f_menu_app_audio added sox.
##            *f_menu_app_text_editors added txt2html, txt2pdbdoc, txt2regex,
##             and txt2tags.
##
## 2013-03-18 *Fixed typo on 1st line #!bin/bash which had an appended comment
##             Thanks to D.J.J. Ringer.
##
## 2013-03-17 *f_how_to_quit_application added option to clear.
##            *f_menu_app_network_config added option to ping -c 10.
##            *f_menu_app_sys_monitors added lsof, hdparm.
##            *f_application_error use echo -n for Y/N questions.
##            *Edit History update and clean up. 
##
## 2013-03-16 *f_menu_app_downloaders added md5sum, sha1sum, md5pass, sha1pass.
##            *f_menu_app_downloaders fixed aria2 install.
##            *f_menu_app_sys_monitors added uuid, dmidecode, lsb, uname, lsmod,
##             printenv, lsusb.
##            *f_menu_app_sys_monitors fixed display for dmidecode, lsb, lsmod,
##             printenv, lsusb.
##            *f_menu_app_network_config added iptables, ufw.
##              
## 2013-03-15 *f_menu_app_network_config added traceroute6, ping.
##
## 2013-03-14 *Main Menu item "License" if file COPYING does not exist,
##             then use web browser, w3m to view license at www.gnu.org.
##
## 2013-03-13 *f_menu_app_image_graphics_applications linuxlogo display menu.
##            *Main Menu item "License" added to display file COPYING.
##
## 2013-03-12 *Main Menu item "License" added to show copyright and license.
##            *f_menu_app_sys_monitors added f_how_to_quit_application.
##            *f_menu_app_text_editors added f_how_to_quit_application.
##            *f_menu_app_sys_monitors added saidar.
##            *f_application_error create installation routine for glances.
##            *f_show_menu supress line-feed at items prompt, fixed $MAX.
##            *f_menu_app_audio_application added avconv.
##
## 2013-03-09 *f_application_error added case statement to install bsdgames
##             if any of the games included in bsdgames are not installed.
##            *Added automatic calculation of revision number, grep -c(ount).
##            *Added sub-menus for Games.
##            *f_quit_app_menu, f_quit_subcat_menu delete "Quit", "Exit"
##             items leave only zero and "Return" because "Quit" is too
##             close to "Quiz" game, and "Exit" was undocumented.
##            *f_show_menu added display new Quit message when in Main Menu.
##            *Main Menu and application category menus changed delimiter
##             so it is obvious to differentiate from application menus.
##            *f_show_menu changed to show help message only for application
##             menus.
##            *Documented all variables used and list of delimiters.
##            *Removed hard-coding of script file-name use $THIS_FILE instead.
##            *f_application_error now extracts package name from $APP_NAME
##             when it includes additional parameters separated by spaces.
##
## 2013-03-07 *f_application_error added trap for error code 1 for sudo.
##            *Added function f_application_run to re-run newly installed apps.
##            *Reworked all application menus to use f_application_run.
##
## 2013-03-06 *f_menu_app_sys_monitors added System tools, cfdisk, parted.
##            *f_menu_app_text_editors added Text tools, colordiff, diff,
##             vimdiff, and wdiff.
##
## 2013-03-04 *Cleaned up displays so text fits on an 80-column wide screen.
##            *f_application_error added error message if installation fails.
##            *f_show_menu started menu item numbering at 1 not zero.
##            *f_show_menu added item 0, to quit.
##            *Deleted item 0, to quit in all f_sub-menus.
##
## 2013-03-03 *Created sub-menu, "Network Category" under Applications menu.
##            *Added Network applications smbclient, smbstatus, testparm.
##            *Added function f_press_enter_key_to_continue.
##            *Added function f_menu_app_press_enter.
##            *Added function f_menu_app_press_enter in application functions.
##            *Deleted statements "read x" in application functions.
##            *f_application_error fixed bad syntax [ $ERROR <> 0 ].
##            *f_application_help fixed bad syntax [ $ERROR <> 0 ].
##            *f_application_help enhanced and clarified error messages.
##
## 2013-02-26 *Added cbm, a system resource monitor, and smbc, file manager
##             for Samba server shared folders.
##            *f_menu_app_text_editors added text editors, ed, emacs, pico, vi.
##            *f_menu_app_spreadsheets_editors added spreadsheets, oleo, slsc.
##            *f_menu_app_calendar-todo added calendars, cal, remind.
##            *f_menu_app_calendar-todo added To-Do list, devtodo.
##
## 2013-02-20 *Created sub-menu, "System Category" under Applications Menu.
##            *Cleaned up menus, sorted items by function.
##            *Added function f_menu_cat_sample_template.
##
## 2013-02-19 *f_application_error, improved error message processing.
##
## 2013-02-18 *Added more applications, cleaned up more code.
##
## 2013-02-17 *Added case string pattern matching for all Internet applications.
##
## 2013-02-14 *Cleaned up listing for readability.
##            *Created sub-menu, "Internet Category" under Applications Menu.
##            *Added Internet application menus for web browsers, bittorrent,
##             downloaders, email, FAX, file transfer, instant messaging,
##             Internet relay chat, news readers, network chat, podcatchers,
##             remote connection and RSS feeders.
##            *Make all application menus into functions rather than using
##             nested until loops.
##            *Added functions f_menu_app_sample_template, f_initvars_menu_app,
##             f_menu_app_internet.
##            *Fixed f_application_error by adding f_initvars_menu_app to
##             prevent return to previous menu rather than return to the same
##             menu where the error occurred.
##
## 2013-02-12 *Created functions for each application menu to allow greater
##             flexibility to re-arrange menu structure and allow the
##             possibility of sub-menus.
##
## 2013-01-29 *Created function f_termcolor to set terminal properties.
##
## 2013-01-28 *f_menu_cat_applications fixed item "Exit".
##
## 2013-01-26 *Used grep to calculate the number of the last menu item.
##            *Created functions show_menu, quit_app_menu, application_help to
##             eliminate repeated code.
##            *Create function f_application_error with an option to install
##             a missing application.
##            *f_application_help, added error trapping to trap lack of help 
##             manual or help messages.
##            *Added item to quit any menu by entering "exit".
##
## 2013-01-24 *Used sed/awk (not echo) to display menu and calculate $MAX.
##            *This took several days to figure out but now I grok awk.
##            *Added a HOW-TO Added new item under General Help.
##
## 2013-01-16 *Edit History, improved sed to display without leading "##" by
##             using substitution of null for "##".
##            *Application menus, finished adding help options.
##            *System menu, deleted application cmatrix.
##            *System menu, added application top.
##            *System menu, added application htop.
##            *System menu, added application glances.
##            *Network menu, added application iftop. 
##            *Games menu, added applications cribbage, boggle.
##            *Games menu, deleted package name debian-jr-games.
##
## 2013-01-15 *Edit History, used sed to display text.
##            *All menus, changed prompt from "Choose 0 to $MAX or name" 
##             to "Enter 0 to$MAX or letters".
##            *Application menus, added help options to all applications
##             accessible from the applications menus.
##
## 2013-01-14 *Main Menu added Black/White screen items.
##
## 2013-01-08 *Case pattern matching for strings is enabled for all menus.
##
## 2013-01-07 *Figured out how to use pattern matching to match input string
##             in case statements.
##
## 2013-01-02 *Put MAX variable inside current until loop to prevent inner
##             loops from changing value on exit.
##            *Do not clear screen before displaying each application menu so
##             that you can see any error messages.
##            *Main Menu added item "About CLI Menu" and get menu items
##             "Help" and "Free disk space" working.
##
## 2013-01-01 *Changed to using until loops because the while loops abnormally
##             exit if read input is not an integer.
##            *Used while loops rather than until loops since continuing to
##             loop and exiting loop is simpler, since you do not need to set
##             conditional variables to an invalid state to force looping.
##
## 2012-12-31 *Created menu driven CLI application launcher.
##            *Case statements drove me crazy, learning pattern matching.
##
